import Head from "next/head";
import NavBar from "@/components/NavBar/NavBar";

export default function Home(hex: number) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="/styles/tailwind.css" rel="stylesheet"></link>
      </Head>
      <NavBar />
      <div
        className="min-h-screen flex justify-center items-center bg-cover"
        style={{ backgroundImage: "url(/images/river.jpeg)" }}
      >
        <div className="bg-white bg-opacity-80 p-8 rounded-lg shadow-md">
          <div className="text-center text-3xl font-bold text-gray-700 mb-4">
            Welcome to my projects website!
          </div>
          <div className="text-center text-gray-700 text-lg mb-6">
            Here is a description of the projects you can check out:
          </div>
          <ul className="list-disc ml-6">
            <li className="mb-2">
              <span className="font-semibold">Skull Keeper</span>
              <p className="text-gray-600 ml-3">
                This is a score keeper for the card game Skull king
              </p>
            </li>
            <li className="mb-2">
              <span className="font-semibold">Calculator</span>
              <p className="text-gray-600 ml-3">
                I thought it would be fun to recreate the calculator on my
                iPhone
              </p>
            </li>
            <li className="mb-2">
              <span className="font-semibold">Doodler</span>
              <p className="text-gray-600 ml-3 max-w-md">
                Websockets sounded interesting, so I made a clone of Drawful by
                Jackbox Games
              </p>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
}
